name: diffsheg
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - addict==2.4.0
    - appdirs==1.4.4
    - asttokens==2.4.1
    - audioread==3.0.1
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - contourpy==1.2.1
    - cycler==0.12.1
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - filelock==3.14.0
    - fonttools==4.51.0
    - fsspec==2024.3.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - huggingface-hub==0.22.2
    - idna==3.7
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - ipython==8.18.1
    - jedi==0.19.1
    - joblib==1.4.0
    - kiwisolver==1.4.5
    - librosa==0.9.2
    - llvmlite==0.42.0
    - lmdb==0.96
    - loguru==0.6.0
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.7
    - mmcv-full==1.6.0
    - numba==0.59.1
    - numpy==1.26.4
    - opencv-python==4.9.0.80
    - packaging==24.0
    - pandas==1.4.2
    - parso==0.8.4
    - pathtools==0.1.2
    - pexpect==4.9.0
    - pillow==10.3.0
    - platformdirs==4.2.1
    - pooch==1.8.1
    - prompt-toolkit==3.0.43
    - protobuf==4.25.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==3.0.0
    - pycparser==2.22
    - pygments==2.17.2
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - regex==2024.4.28
    - requests==2.31.0
    - resampy==0.4.3
    - safetensors==0.4.3
    - scikit-learn==1.4.2
    - scipy==1.10.1
    - sentry-sdk==2.0.1
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - soundfile==0.12.1
    - stack-data==0.6.3
    - termcolor==2.1.1
    - threadpoolctl==3.5.0
    - tokenizers==0.13.3
    - tomli==2.0.1
    - torch==1.13.1+cu117
    - torchaudio==0.13.1+cu117
    - torchvision==0.14.1+cu117
    - tqdm==4.66.2
    - traitlets==5.14.3
    - transformers==4.31.0
    - typing-extensions==4.11.0
    - umap==0.1.1
    - urllib3==2.2.1
    - wandb==0.13.10
    - wcwidth==0.2.13
    - yapf==0.40.2
    - zipp==3.18.1
